# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=100)),
                ('time_to_send', models.DateTimeField()),
                ('conditional_clause', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
    ]
