# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='completed_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='total_number',
            field=models.IntegerField(default=0),
        ),
    ]
